{% set name = "GeoAlchemy2" %}
{% set version = "0.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GeoAlchemy2-{{ version }}.tar.gz
  sha256: 31c2502dce317b57b335e4eb87562d501fa39e46c728be514d9b86091e08dd67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.4
    - packaging

test:
  imports:
    - geoalchemy2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://geoalchemy-2.readthedocs.io/en/latest/
  summary: Using SQLAlchemy with Spatial Databases
  dev_url: https://github.com/geoalchemy/geoalchemy2
  license: MIT
  license_file: COPYING.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - MattTriano
