{% set name = "GeoAlchemy2" %}
{% set version = "0.9.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "56f969cf4ad6629ebcde73e807f7dac0a9375c79991b4f93efab191f37737a00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - sqlalchemy >=1.1

test:
  imports:
    - geoalchemy2

about:
  home: "https://geoalchemy-2.readthedocs.io/en/latest/"
  license: MIT
  license_family: MIT
  license_file: COPYING.rst
  summary: "Using SQLAlchemy with Spatial Databases"
  doc_url: https://geoalchemy-2.readthedocs.io/en/latest/
  dev_url: https://github.com/geoalchemy/geoalchemy2
  
extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - matttriano